### ISSUE TITLE
missing ptan dependency

### ISSUE THREAD

**Issue by tyoc213** [josiahls/fast-reinforcement-learning-2#1]
`ptan` is not in dependencies, so after I installed on my conda environment from cloned repo with `pip install -e .`

![image](https://user-images.githubusercontent.com/506234/104680635-f8501800-56b5-11eb-8f06-117d75ccdb4c.png)

doing `pip install ptan` outputs

```
$ pip install ptan
Collecting ptan
  Downloading ptan-0.7.tar.gz (20 kB)
Requirement already satisfied: torch==1.7.0 in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from ptan) (1.7.0)
Requirement already satisfied: gym in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from ptan) (0.18.0)
Collecting atari-py
  Downloading atari-py-0.2.6.tar.gz (790 kB)
     |████████████████████████████████| 790 kB 38 kB/s 
Requirement already satisfied: numpy in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from ptan) (1.19.1)
Collecting opencv-python
  Downloading opencv_python-4.5.1.48-cp38-cp38-manylinux2014_x86_64.whl (50.4 MB)
     |████████████████████████████████| 50.4 MB 1.4 MB/s 
Requirement already satisfied: future in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from torch==1.7.0->ptan) (0.18.2)
Requirement already satisfied: typing_extensions in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from torch==1.7.0->ptan) (3.7.4.3)
Requirement already satisfied: dataclasses in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from torch==1.7.0->ptan) (0.6)
Requirement already satisfied: Pillow<=7.2.0 in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from gym->ptan) (7.2.0)
Requirement already satisfied: pyglet<=1.5.0,>=1.4.0 in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from gym->ptan) (1.5.0)
Requirement already satisfied: scipy in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from gym->ptan) (1.5.2)
Requirement already satisfied: cloudpickle<1.7.0,>=1.2.0 in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from gym->ptan) (1.6.0)
Requirement already satisfied: six in /home/tyoc213/miniconda3/envs/fastai/lib/python3.8/site-packages (from atari-py->ptan) (1.15.0)
Building wheels for collected packages: ptan, atari-py
  Building wheel for ptan (setup.py) ... done
  Created wheel for ptan: filename=ptan-0.7-py3-none-any.whl size=23503 sha256=4fc790231e0df2795edfb512a1db54c188e98fc7708ddef8c7e3a36e3c10884b
  Stored in directory: /home/tyoc213/.cache/pip/wheels/4e/c0/b7/67750bb433409ebfe80cefcb7403aec8014372ff47d5efe8fb
  Building wheel for atari-py (setup.py) ... done
  Created wheel for atari-py: filename=atari_py-0.2.6-cp38-cp38-linux_x86_64.whl size=2812157 sha256=386ada60952333772a5570ae1c43b29abd8f59aac21fae8791c50913ad1ccc78
  Stored in directory: /home/tyoc213/.cache/pip/wheels/7f/5e/27/2e90b9887063d82ee2f9f8b2f8db76bb2290aa281dc40449c8
Successfully built ptan atari-py
Installing collected packages: atari-py, opencv-python, ptan
Successfully installed atari-py-0.2.6 opencv-python-4.5.1.48 ptan-0.7
```

After fixing that I can continue executing the notebook 03_basic_agents.

extra Q: if just starting RL with this lib, what next steps do you recommend?

**Comment by josiahls** [comment]
Hi

## About the Issue
`ptan` is not going to be a final dependency. In the README I have `source activate fastrl && pip install ptan --no-dependencies && python setup.py develop`. **Let me know if there is a change in the README to make this more obvious/ or maybe explaining why we are installing ptan separately is desired.**

The main reason is that if I add it to the setup.py, it may try to install all of ptan's dependencies which I am not interested in have download. Again, ptan is a temporary dependency. We are using it as a baseline for both model migration as well has our fastai plugin env iteration. 

Regardless, this is a good question to ask, and having this issue here can clarify this for others. 
Also since you are forking this repo as opposed to  the `https://github.com/josiahls/fast-reinforcement-learning` this lib will be broken constantly and generally be harder to work with since I'm trying a bunch of different things all the time, hence the reason there isn't a pip package for this version yet. 

Most importantly, assuming that my migration for `DADS` goes well, in Feb, I plan to redo **everything**.
 
I need to do this because I have learned what all these RL (and HRL) models actually need. You may notice certain objects have messy source code and this is a result of trying a bunch of different stuff, and making changes that "just barely work". This models also train slower (time wise) because there are a bunch of inefficient ways of iterating/training the models.

## Your question of RL
I am on https://forums.fast.ai/t/discord-chat/34779 #jokellum I recommend being part of that server its very active and Jeremy is on there as well as the rest of the devs. I will be chatting on there. Just note that fastrl is not part of the fastai org and neither am I, I just really like fastai and really like Jeremy Howards software dev methodology in relation to ML. 
I recommend looking at the actual [ptan](https://github.com/Shmuma/ptan) library. It is developed used by the author of [Deep Reinforcement Learning Hands-On](https://www.amazon.com/Deep-Reinforcement-Learning-Hands-optimization/dp/1838826998/ref=sr_1_1_sspa?crid=3NQFCFBTCKLSN&dchild=1&keywords=hands+on+reinforcement+learning+with+python&qid=1610722792&sprefix=hands+on+reinf%2Caps%2C162&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzUk01V05QVk9DN1FTJmVuY3J5cHRlZElkPUEwMDM1MDAxMVlHREdEVUtQQjkyWCZlbmNyeXB0ZWRBZElkPUEwOTk5NTg2MVNEUEVHMFFMMEk1USZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=) and I recommend looking at his library [Deep-Reinforcement-Learning-Hands-On](https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On) which is where a bunch of these models are being migrated from/tested against.

In Feb (if DADS goes well), this library may pattern its models similarly to [spinning up](https://github.com/openai/spinningup/tree/master/spinup/algos/pytorch). All of the models will be refactored, and hopefully have more fleshed out explanations. Its implementations seem efficient, however the training could be improved on.

I will close this for now because I answered why ptan is not set as a dep in the setup.py because it only temporary and will not make it into version 2.0 release. But feel free to respond here!

**Comment by tyoc213** [comment]
What you mean by migration to DADS? I mean, I see that you already have some work on that path, so I guess you will make a refactor of some type?



> Also since you are forking this repo as opposed to the `https://github.com/josiahls/fast-reinforcement-learning` this lib will be broken constantly and generally be harder to work with since I'm trying a bunch of different things all the time, hence the reason there isn't a pip package for this version yet.

I cloned this repo because I assumed that https://github.com/josiahls/fast-reinforcement-learning is only compatible with fastai1, but I'm working with v2.

For the moment Im running each notebook and seeing that "it executes", know veery little about RL so I want to see if later I can "plug" some book problems or others in one of the RL algos.

**Comment by josiahls** [comment]
DADS is another HRL algorithm I am adding to fastrl v2. It is similar to DIAYN which seems to work "ok", its missing a meta learner to properly solve tasks. Presently DADS (https://github.com/google-research/dads) has only a tf implementation. I am making a pytorch version, and consequently making it also fastrl compatible. 

> I cloned this repo because I assumed that https://github.com/josiahls/fast-reinforcement-learning is only compatible with fastai1, but I'm working with v2.

Correct, this repo is compat only with fastai2 while the older one only works with fastai1.

I do plan to do the giant refactor of this repo iteratively. So all the older notebooks and source code I might put into a "old" directory so both me and others can verify that the new refactored models are in fact better (both in terms of convergence but also actual wall time training speed). Either that or I'll simply make an archive branch before the refactor. Haven't decided yet. Regardless, you will have access to the original way everything was setup.

Once DADS is added I will let you know here when I plan to do the refactor.

The current rough timeline is:
- Add DADS
- (maybe finish adding some remaining DQN models, should be straight forward though and they already exist in fastrl1)
- Refactor everything
- Merge into the original fast-reinforcement-learning repo (add pip and conda)
